### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by mensinda** [Kev/clang-flags#6] opened 2015-01-30 21:11 UTC
Trying to install [linter-clang](https://github.com/AtomLinter/linter-clang/issues/43) and/or [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang/issues/34) results in very similar install errors.

It seems like the clang-flags package is causing this issue in both cases.

My System:

OS: Arch Linux 64 bit
Atom version 0.176.0.r91.gb02d0e3-1

Clang Version: 3.5.1
GCC Version: 4.9.2

My system default compiler is GCC.

**Comment by mensinda** [comment] 2015-01-31 18:52
Upgrading pathwatcher to version `3.0.1` solved the _install_ problem for me.

I do not know if this fixes the problem because both plugins wont work and there are warnings containing `Error: Cannot find module '../build/Release/pathwatcher.node'` in the console.

I never wrote a plugin for atom and I always installed plugins from the GUI so it is possible that I did something wrong.

**Comment by yandy** [comment] 2015-02-04 02:21
+1

**Comment by jplatte** [comment] 2015-02-06 23:05
+1

**Comment by gnzlbg** [comment] 2015-02-09 11:24
+1

**Comment by Kev** [comment] 2015-02-09 11:35
I merged the pathwatcher patch, thank you. Closing the issue, as I assume the patch was sufficient, let me know if not.

**Comment by gnzlbg** [comment] 2015-02-09 12:21
I still get the same error:

``` bash
> runas@1.1.0 install /private/var/folders/mm/y444qqwd0kn52fycyz6nsph40000gn/T/apm-install-dir-11519-62713-wqibdu/node_modules/autocomplete-clang/node_modules/clang-flags/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o

In file included from ../src/main.cc:1:
../../nan/nan.h:623:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/gnzlbg/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:1936:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/main.cc:1:
../../nan/nan.h:622:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../../nan/nan.h:617:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../../nan/nan.h:1993:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
  if (str->IsExternalAscii()) {
           ^~~~~~~~~~~~~~~
           IsExternal
/Users/gnzlbg/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:1900:8: note: 'IsExternal' declared here
  bool IsExternal() const;
       ^
In file included from ../src/main.cc:1:
../../nan/nan.h:1994:23: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
    const v8::String::ExternalAsciiStringResource* ext;
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ExternalStringResource
/Users/gnzlbg/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:1936:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/main.cc:1:
../../nan/nan.h:1995:16: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'
    ext = str->GetExternalAsciiStringResource();
          ~~~  ^
../../nan/nan.h:1996:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
6 errors generated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/gnzlbg/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/gnzlbg/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/mm/y444qqwd0kn52fycyz6nsph40000gn/T/apm-install-dir-11519-62713-wqibdu/node_modules/autocomplete-clang/node_modules/clang-flags/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/gnzlbg/Downloads/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/gnzlbg/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/gnzlbg/Downloads/Atom.app/Contents/Resources/app/apm/.apmrc" "--userconfig" "/Users/gnzlbg/.atom/.apmrc" "install" "/private/var/folders/mm/y444qqwd0kn52fycyz6nsph40000gn/T/d-11519-62713-unkbjt/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! runas@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/mm/y444qqwd0kn52fycyz6nsph40000gn/T/apm-install-dir-11519-62713-wqibdu/npm-debug.log
```

**Comment by jplatte** [comment] 2015-02-09 18:01
I'm having the same issue :/

**Comment by Queuecumber** [comment] 2015-02-10 18:02
Also having this issue

**Comment by yukula** [comment] 2015-02-14 19:29
+

**Comment by KarateSnowMachine** [comment] 2015-02-15 23:43
I think the workaround for this is to merge Kev/clang-flags with wanderer2/clang-flags (wanderer2/clang-flags is specified by clang-autocomplete) 

The wanderer2 repo is a bit out of date wrt to the Kev repo. 

I'm still new to apm and node.js,  but I believe this gets me past the build error. I still need to test the actual plugin to see if it works.

Edit: fixing fat fingered typos from phone typing

**Comment by KarateSnowMachine** [comment] 2015-02-16 02:27
EDIT: this patch is no longer necessary; keep scrolling down for further discussion. 

Well, I've confirmed that this fix works: 

``` diff
~/atom-test/autocomplete-clang$ git diff
diff --git a/package.json b/package.json
index 8c0ca5e..bfa5314 100644
--- a/package.json
+++ b/package.json
@@ -12,6 +12,6 @@
   "dependencies": {
     "atom-space-pen-views": "^0.20.0",
     "underscore-plus": "1.x",
-    "clang-flags": "git://github.com/wanderer2/clang-flags.git"
+    "clang-flags": "git://github.com/KarateSnowMachine/clang-flags.git"
   }
 }
```

After doing an `apm link`, I can see the package is installed and I see a menu item for it. However I'm still not getting any completions and I'm not sure how to debug that further. That's another topic though. 

Edit: clang wasn't on my path :(   completions are working now.

**Comment by gnzlbg** [comment] 2015-02-16 09:46
Installing works for me too.

**Comment by Kev** [comment] 2015-02-16 13:00
Is there anything in the KarateSnowMachine repo that isn't in wanderer2 or my repos? Also, does it work if you directly reference my repo by git, instead of either of the forks or my old release?

I'm still trying to work out the optimal thing to do here (not helped by a lack of time, I admit) is.

**Comment by jplatte** [comment] 2015-02-16 13:09
@Kev: The only difference is the pathwatcher version dependency: https://github.com/KarateSnowMachine/clang-flags/compare/wanderer2:master...master

**Comment by Kev** [comment] 2015-02-16 13:24
Thanks. And that patch is on my master already, I believe, so (other than compdb stuff probably not working properly), pointing the clang-flags dependency for autocomplete-clang directly at my repo instead of the fork should presumably allow it to install?  And I could merge the pending PR from wanderer2 to get compdb working (together with extending it slightly so it'll pull in defines too). I'll go ahead with this plan unless anyone shouts that it's a bad idea.

**Comment by KarateSnowMachine** [comment] 2015-02-16 14:23
I just noticed the forks diverged slightly and tried to do a blind merge, so I'm not sure exactly what the implications of that merge were. 

I didn't try to point it straight at your repo, but it seems like that might work too. What's also interesting is the developer of autocomplete-clang also has a fork of clang-flags but he doesn't point autocomplete-clang at it. 

edit: looks like autocomplete-clang dev has already repointed his package file to your repo: https://github.com/yasuyuky/autocomplete-clang/commit/c034a3c45daa4dd42b154ee59c77543b03228c0a

**Comment by KarateSnowMachine** [comment] 2015-02-16 14:45
I deleted my fork as this problem appears to have been solved upstream in autocomplete-clang. I think it's likely safe to close this issue now. 

Thanks for taking a look at this.

**Comment by Kev** [comment] 2015-02-16 17:05
I think I've now merged in all the changes to my branch as well.

Thanks to everyone who's looked at this.

**Closed as completed by Kev** 2015-02-16 17:05 UTC
